#!/usr/bin/env bash
set -euo pipefail

TIMESTAMP="$(date -u +%Y%m%dT%H%M%SZ)"

UV_PATH="${UV_PATH:-}"
if [[ -z "$UV_PATH" ]]; then
  UV_PATH="$(command -v uv || true)"
fi
if [[ -z "$UV_PATH" || ! -x "$UV_PATH" ]]; then
  echo "Unable to find executable uv. Set UV_PATH=/path/to/uv and rerun." >&2
  exit 1
fi

RUN_ROOT="/home/carlos/Clone/uv_vae/artifacts/ddbR9-b2_${TIMESTAMP}"
PARQUET_PATH="/home/carlos/Clone/uv_vae/data/ddbR9-b2-ppm0029.featuremap.parquet"
FEATURE_SPEC_PATH="/home/carlos/Clone/uv_vae/ml_features.json"
TRAIN_OUTPUT_DIR="${RUN_ROOT}/training"
CLUSTER_OUTPUT_ROOT="${RUN_ROOT}/clustering"
TRAIN_ROW_FILTER="st = 'MIXED' AND et = 'MIXED' AND FILT = 1"
CLUSTER_ROW_FILTER="st = 'MIXED' AND et = 'MIXED' AND FILT = 1"
TRAIN_USE_ALL=0
TRAIN_SAMPLE_ROWS=100000
TRAIN_EPOCHS=1000
TRAIN_BATCH_SIZE=4096
TRAIN_LATENT_DIM=16
TRAIN_HIDDEN_DIMS="512,256,128"
TRAIN_LEARNING_RATE=1e-3
TRAIN_KL_WEIGHT=0.05
TRAIN_FRACTION=0.9
PIPELINE_SEED=42
TRAIN_SEED="$PIPELINE_SEED"
TRAIN_THREADS=8
CLUSTER_SEED="$PIPELINE_SEED"
CLUSTER_USE_ALL=1
CLUSTER_SAMPLE_ROWS=1000000
CLUSTER_THREADS=8
DEVICE=auto
EMBED_BATCH_SIZE=4096
SCAN_BATCH_ROWS=100000
UMAP_FIT_ROWS=250000
PLOT_ROWS=100000
UMAP_N_NEIGHBORS=30
UMAP_MIN_DIST=0.05
UMAP_METRIC=euclidean
HDBSCAN_MIN_CLUSTER_SIZE=250
HDBSCAN_MIN_SAMPLES=25
SIGPROFILER_CPU=8
COSMIC_VERSION=3.5
GENOME_BUILD=GRCh38
DUCKDB_MEMORY_LIMIT=12GB
COLOR_COLUMNS="BCSQ,RAW_VAF,DP,SMQ_BEFORE,SMQ_AFTER,EDIST,MAPQ,SNVQ"

export RUN_ROOT
export UV_PATH
export PARQUET_PATH
export FEATURE_SPEC_PATH
export TRAIN_OUTPUT_DIR
export CLUSTER_OUTPUT_ROOT
export TRAIN_ROW_FILTER
export TRAIN_USE_ALL
export TRAIN_SAMPLE_ROWS
export TRAIN_EPOCHS
export TRAIN_BATCH_SIZE
export TRAIN_LATENT_DIM
export TRAIN_HIDDEN_DIMS
export TRAIN_LEARNING_RATE
export TRAIN_KL_WEIGHT
export TRAIN_FRACTION
export PIPELINE_SEED
export TRAIN_SEED
export TRAIN_THREADS
export CLUSTER_SEED
export CLUSTER_USE_ALL
export CLUSTER_SAMPLE_ROWS
export CLUSTER_THREADS
export DEVICE
export EMBED_BATCH_SIZE
export SCAN_BATCH_ROWS
export UMAP_FIT_ROWS
export PLOT_ROWS
export UMAP_N_NEIGHBORS
export UMAP_MIN_DIST
export UMAP_METRIC
export HDBSCAN_MIN_CLUSTER_SIZE
export HDBSCAN_MIN_SAMPLES
export SIGPROFILER_CPU
export COSMIC_VERSION
export GENOME_BUILD
export DUCKDB_MEMORY_LIMIT
export COLOR_COLUMNS

export PYTHONHASHSEED="${PYTHONHASHSEED:-$PIPELINE_SEED}"
export CUBLAS_WORKSPACE_CONFIG="${CUBLAS_WORKSPACE_CONFIG:-:4096:8}"
export OMP_NUM_THREADS="${OMP_NUM_THREADS:-1}"
export MKL_NUM_THREADS="${MKL_NUM_THREADS:-1}"
export OPENBLAS_NUM_THREADS="${OPENBLAS_NUM_THREADS:-1}"
export NUMEXPR_NUM_THREADS="${NUMEXPR_NUM_THREADS:-1}"

bash scripts/run_train_then_cluster.sh --cluster-row-filter "$CLUSTER_ROW_FILTER"

minSNVQ=40
maxSNVQ=999
"$UV_PATH" run python scripts/plot_trinuc96_snvq_histograms.py \
  --parquet-path "$PARQUET_PATH" \
  --row-filter "st = 'MIXED' AND et = 'MIXED' AND FILT = 1" \
  --min-snvq "$minSNVQ" \
  --max-snvq "$maxSNVQ" \
  --output-path "${RUN_ROOT}/trinuc96_snvq_histograms.png"
